### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mugekurtipek** [bounswe/bounswe2015group4#112]
Can you please review my code in 12c8fbe40a5b133ddd7f65c0713df0899f5d3ed5 ?

Thanks!

**Comment by mrtcnnccn** [comment]
Started

**Comment by mrtcnnccn** [comment]
-Model classes are all clear and coherent with the ones in the database. They are providing an easy method for communicaton between database and android. However, you may delete all the unrequired parts instead of commenting, and you can change the place of field declarations in Group_Detail.class to top.

-The method in the API.class is designed nice and it preservers the structure of the class.

-The major updates in GroupActivity were required as you do. Now, that class is explicit.

-In GroupActivity.class there is the getBitmapUrl method. As we first designed, it was so slow to handle the process. So we decided to use Picassa for the purpose. You are using Picassa in the other class. Now, that method can be completely removen in order to cause no further problems.

-The usage of Picassa in the PartiActivity class can be generalized and be provided as a Util function, if possible. So, others also use that library in a proper way.

-In member adapter, instead of running it with member names and photos, you could run it with the whole Profile class instances. So that, if we need further things to show up, we can easily add. This may cause different bugs.

-In GroupFrag.java you can use Java's own function to split the string into an array.

-This part was working nice while we were demonstrating our demo. There was no crucial features missing.

-Your names for methods, variables and classes are self-explanatory and nice. However, in some parts you may write some basic comments.

-You can improve documentation with using Javadoc.

-You may be unit testing your splitting for the string which I mentioned above.

-There are some warnings in the code, but in general there is no errors or bugs detected.

-Thanks for your contribution!!!

**Comment by mugekurtipek** [comment]
Thanks for your review, I'll review my code with respect to your comments!

**Comment by mugekurtipek** [comment]
done
