### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mrtcnnccn** [bounswe/bounswe2015group4#114]
Can you review my code in this commit : 1c3379246e30d7f5c626752e72a8c7d44810ac99?
Thank you.

**Comment by berfubuyukoz** [comment]
Started.

**Comment by berfubuyukoz** [comment]
Code clarity:

The code clarity is high. I read and understood the code easily. Additions was made to true portions of the code, which helped maintain readibility. 

Bugs: There is no bug.

Missing Features:

No missing feature. Intended additions are successfully done: Joining to an event, leaving an event,  listing participants of an event, is done, logout fixed. 

Coding convention:
Variable names.
Variable names are meaningful, names are related to the objects they refer to.
Indentation
Indentation is good. I easily see the limits of the methods, dcopes of the variables, that helps adaptation process to the code.
Comments
Comments are added. when necessary for example as a reminder for a future feature that needs to be added.
Coverage with unit test:
You can add a unit test for example for “joining an event” feature.
Modification:
For example I can discard the Bundle code that assigns Intent extras to corresponding variables, I could pull their values when sending a request to get event details. Bur I wouldn’t do that since not using a request is more fast when there is another way like sending an already reached variable among activities by using Intent extras.
What is your opinion about the style used in constructs (e.g., classes, loops, methods, etc.)
The style used is neat. Coder planned the steps to be taken and then reflected that clarity in his mind to the code. So the code consists of well-built modules that help define the units of tasks in the activity.
Run one or more of code analysis tools such as: (Android’s analyzer is used)
Unused import sentences can be deleted for a more compact code.
Android suggests use of “android resources” instead of strings as parameter in setText() method. It basically suggests us to create a strings.xml file and declare strings we will use. So we can call these strings with their declaration names. But as far as I understand it did not affect performance on the context of the code since the  string is not called repeatedly.

Eline sağlık :100:
