### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by berfubuyukoz** [bounswe/bounswe2015group4#115]
Can you review my code on commit on the link:

https://github.com/bounswe/bounswe2015group4/commit/bb8148a72a58bad49c5c1ea5a85774b297886c23?diff=unified

Thank you :)

**Comment by mugekurtipek** [comment]
The API function that you created is good and compatible with the other functions in the API class. Also I noted that you preserved the name convention that we created in API class. 
However, in EventActivity.java class you should make some improvements. Please add or fix following issues:
-Delete the import statements that you are not using. (e.g. import com.parse.FindCallback since we don't use Parse framework anymore)
-Rename the variable names. descrip or parti_number are not very clear for someone who are not familiar with the code.
-Remove the unused global variables. (e.g. byte[] data)
-It is more memory efficient to make an API call for event details, rather than sending all information about the event via bundle. Actually you are doing both API call and sending with bundle from the previous intent. I suggest you to choose one of the options and I'm suggesting the API call.
-While creating error logs try to be more specific about the error. (e.g. rather than  Log.d("Event", "error") you can use  Log.d("Event", "The response is empty");
-You can improve the indentation. For Android Studio there is a short cut for the indentation: in Code segment choose Auto-Indent Lines.
-You can improve code documentation with using Javadoc and leaving comments.
Rather than these, the code seems very familiar to me since you follow a compatible style with the remaining of the project. I can easily modify your code. I run the code and couldn't find any bugs. Unit tests are missing. Tests should cover the extreme cases like there is no data to show or like the data is too long. I run IntelliJ Code Analyzer and it finds lots of warnings in your code, specially in EventActivity class. I suggest you to revisit that class.
Looking forward to hear from you!
Ellerine saglık:)

**Comment by berfubuyukoz** [comment]
Hi Müge, I appreciate your valuable comments, I definitely learnt from it and it will surely help improve my coding style. I'll  apply fixations you recommend as soon as I can.
