### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mertimre** [bounswe/bounswe2015group4#117]
Can you check my commit number 7922615

**Comment by furkancaymaz** [comment]
Started

**Comment by furkancaymaz** [comment]
Mert, first of all thanks for your contribution, it's a great piece of code which structs the base of event page. 
The code is very clear to understand, especially I want to emphasize that commenting the code will make much more easier to understand this high clarified code and also no bugs appeared to me. 
Evaluating the code with respect to missing features is not fair enough I think, since it has been a part of a more detailed thing, but even I look in a more detailed way, I couldn't notice anything missing here. I think, all just are implemented really well. 
Indentation is arranged good as well, naming and everything is consistent. The only drawback I can say that although commenting has not been something very attractive, which is quite necessary as you already know, I believe :) I may recommend you to comment more, which shouldn't mean the code is hard to understand necessarily.
The code is easy to modify according to the needs of projects in the future, since it has been simple and well structured. 
Testing units may be added, I guess. Addition to that there are also some commented code pieces, which are not used. Deleting those to get more compact structure may be considered. 

All in all, it is a really good commit for a group project: Well structured, so that easy to modify, definitely useful.
