### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mrtcnnccn** [bounswe/bounswe2015group4#120]
Can you review my code in this commit : a6d2ac21d889ca3605cd7b21a45ff8a2eab4d253?
Thank you.

**Comment by tszyanalau** [comment]
Started.

**Comment by tszyanalau** [comment]
Things to appreciate:
-It's a massive work for updating and retrieving information from the database. I really appreciate it because I am bad in doing the android back-end.
-Logs are used properly which are convenient and efficient for debugging when errors occur.
-Some variables are defined with proper type, like defining static variables for users and posts.
-The indentations are good, naming of variables is easy to understand.

However I would like to suggest the followings:
-Add checks for the number of post/ photos/ users, if it is zero, wordings like"No posts/ photos/ users to show" shall be displayed on the screen.
-Code documentation can be improved with the use of javadoc and leaving comments, so that others can understand it quickly and fix it if there is any bug. 
-If possible, describe the error in the log in detail, but not just "error".
-Add checks for empty comment and post. Maybe we can warn the user , ask he/her to re-type and don't allow the submission.

Thanks for your contribution!
