### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by tszyanalau** [bounswe/bounswe2015group4#121]
Berfu, can you please review my code under commit 32f9a8e

**Comment by berfubuyukoz** [comment]
Started.

**Comment by berfubuyukoz** [comment]
Hi Amy, 
I reviewed your code.
Firstly, I think your code has high readability. I easily understood the xml files thanks to your structured and neat style. The names of views, buttons and layouts are meaningful, helps me understand for what they stand for. 
In addition, you are following a certain plan for every java files, that helps us get used to it and make modifications on them fast. You stick to the requirements which is very nice, so when we open and see your code it provides us a model of what we need to do in that page, for example you create Intents and everything. 
When I run your code, I see there is no bug. 
You can add some comments to especially your java code sometimes it was a bit difficult to comprehend. 
Actually I was able to modify one of your codes earlier, the one with the switch-case  at HomePage.java, that implies your code clarity is good I could easily accomodate, and move on.
In java files there is no warning about your side so you don’t write unnecessary code, that prevents mess.
Indentation  of your code is good I think. I can track hierarchy on xml code like which image view is within which layout, that can be seen clearly. 
I actually did not find a sample unit test case for your code since you generally deal with the structure and connections between the pages rather than data management or algorithms.
I used IntelliJ Code Analyzer, there are not much warnings, just some recommendations about adding features to some xml modules, that supports right-to-left layouts. I suggest you review these warnings.
Thank you for all of your contribution, I realize how fine tricks can be done when using xml indeed :)
